// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpotorhyucwrivwdzelp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFwb3Rvcmh5dWN3cml2d2R6ZWxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNzk1MjQsImV4cCI6MjA2Mjc1NTUyNH0.YTOKwxEfN1syHIiQi64WMVx0uKMIKBDgz5i1fud0ZYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);